version: '3'

services:
  mongo: 
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: "root"
    #   MONGO_INITDB_ROOT_PASSWORD: "root"
    #   MONGO_INITDB_DATABASE: trip
  app:
    image: trip:v1
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    # environment:
      # - MONGO_URI=mongodb://admin:1234567890@mongo:27017